#+BEGIN_HTML
---
layout: post
title: 2016-04-04-mysql安装
---
#+END_HTML
#+OPTIONS: toc:nil
* mysql安装
  在Ubuntu上的安装跟其他包一样。mysql分为server和client，在安装server的时候会自动安装client。
  #+BEGIN_SRC sh
    sudo apt-get update
    sudo apt-get upgrade
    sudo apt-get install mysql-server
  #+END_SRC
  默认情况下，mysql server只允许本地localhost(127.0.0.1)连接，如果需要通过ssh远程连接上数据库的话，需要修改配置文件my.conf的bind-address参数。
* 增强mysql的安全性
  #+BEGIN_SRC sh
  sudo mysql_secure_installation
  #+END_SRC
  这个脚本会问一些问题，然后给出可以选择的选项，比如说为root用户添加密码、只允许root在localhost上登录、删除匿名用户和test数据库等。可以看出这些问题的建议答案都是yes，是引导用户增加mysql的安全性。  
  
* mysql使用
** 连接
   #+BEGIN_SRC sh
      mysql -h host -P port -u user_name -p password   
    #+END_SRC
** 连接的错误
*** Can't connect to MySQL server on '192.168.0.102' (61)
    1. 在mysql server机器上尝试本地连接
       #+BEGIN_SRC sh
       mysql -u user_name -p
       #+END_SRC
       如果本地连接可以连接上，说明mysql server是启动并且工作正常的。
    2. 在client端尝试ssh连接server机器
       如果能连上，说明网络是没有问题的。否则查看是不是防火墙设置的问题
    3. 查看mysql的配置文件
       默认情况下，mysql server只允许本地连接，修改my.conf的bind-address参数为：<code> bind-address = 0.0.0.0 </code>。bind-address指定ip的话，只允许指定的ip连接mysql server，修改为0.0.0.0的意思是允许所有的ip地址连接上server。
*** ERROR 1130 (HY000): Host '192.168.0.100' is not allowed to connect to this MySQL server
    当前的host不允许连接上server。
    1. 以root用户登录，查看mysql.user表中是不是没有在当前host上有效的user。
       #+BEGIN_SRC sh
         select User,Host from mysql.user;
       #+END_SRC
       如果没有的话，增加用户并且赋予权限。[[*%E5%88%9B%E5%BB%BA%E7%94%A8%E6%88%B7][创建用户]]
       
*** ERROR 1045 (28000): Access denied for user 'guang'@'192.168.0.100' (using password: YES)
    1.password不对
   
** 创建用户
   root用户的权限太大，一般都是创建一个新用户，设置密码然后将部分权限下发给新用户，client端以这个用户的身份登录。
   #+BEGIN_SRC sh
     create database testdb;
     create user 'testuser'@'localhost' identified by 'password';
     grant all on testdb.* to 'testuser';
     FLUSH PRIVILEGES;
   #+END_SRC
   上面的命令创建了testuser客户，连接密码是password，允许他在localhost这台机器上登录，给他的权限是对于testdb这个数据库的全部权限。
