* docker安装
  - 通过curl下载docker安装包。
  #+BEGIN_SRC shell
  curl -fsSL https://get.docker.com/ | sh
  #+END_SRC
  - 验证安装
    #+BEGIN_SRC shell
    docker run hello-world
    #+END_SRC
    需要sudo权限。如果希望以xxx用户的身份也能运行，执行命令：
    #+BEGIN_SRC shell
    sudo usermod -aG docker xxx    
    #+END_SRC
    将xxx添加到docker的用户组中。
* Images & Containers
  - container
    极简的linux系统。
  - image
    可以转载到container的软件。image可以是简单的执行一次就结束的程序，比如说hello-world，也可以是非常复杂的比如说是database这种等待用户输入，返回结果，一直循环下去运行的程序。
  在执行docker run hello-world命令时：
  - 检查本地是否有hello-world这个image
  - 如果没有，从docker hub上下载。国内的download速度很慢啊，托某长城的福
  - 将hello-world装载到container中，并且执行
* docker hub
  docker hub类型git hub，可以创建账号，建立个人仓库，将自己创建的image push到docker hub上分享，也可以通过docker pull从docker hub上下载image。


    
* docker命令
  - docker images
    列出已经下载到本地的所有image
  - docker login --username --email --password
    登录docker hub
  - docker tag 
    给docker image id起别名，通过名字可以找到对应的image
  - docker push
    push image到docker hub
  - docker pull
    从docker hub上下载image
  - docker run
    在container中执行image



